apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #google cloud key e1060c51edfbce8751c06aef1244f3d2b9e7fdde
  # google cloud image address us.gcr.io/dynamic-density-277214/auth
  # googleCloudBuild:
  #   projectId: dynamic-density-277214
  artifacts:
    - image: berlink2/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: berlink2/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: berlink2/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
